name: Build and Deploy Docker Image to EC2

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and push Docker image
      run: |
        docker stop $(docker ps -a -q) || true
        cd react-app
        docker build -t react-app .
        docker run -d -p 3000:3000 react-app

