name: Build and Deploy to Separate Runners

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:
  # Job for Docker-AWS-Runner
  build-on-aws-runner:
    runs-on: Docker-AWS-Runner
    name: Build and Deploy on AWS-Runner for Docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and push Docker image
      run: |
        docker stop $(docker ps -a -q) || true
        cd react-app
        docker build -t react-app .
        docker run -d -p 3000:3000 react-app
    
# Job for Nginx-AWS-Runner
  build-on-nginx-aws-runner:
    runs-on: Nginx-AWS-Runner
    name: Build and Deploy on Nginx-AWS-Runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup and deploy with Nginx
        run: |
          cd react-app
          npm install
          npm run build
          sudo cp -r build/* /var/www/react/
          sudo systemctl restart nginx
